name: Premium Page Tests

on:
  push:
    branches: [ 'main', 'master' ]
  pull_request:
    branches: [ '*' ]
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm ci
      - name: Save node_modules
        run: tar -czf node_modules.tar.gz node_modules
      - uses: actions/upload-artifact@v4
        with:
          name: node_modules
          path: node_modules.tar.gz

  premium_page_test:
    needs: install
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.52.0-noble
      options: --user 1001
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Download node_modules
        uses: actions/download-artifact@v4
        with:
          name: node_modules
      - name: Extract node_modules
        run: tar -xzf node_modules.tar.gz
      - name: Run tests
        run: npm run tests:docker
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30